// ---------------------------------------------------------------------------
// Base de données des vinyles
// Chaque vinyle contient toutes les informations nécessaires pour la page produit.
// Le "slug" sert d'identifiant dans l'URL : /produit/thriller
// ---------------------------------------------------------------------------

export const products = [
    {
        id: 1,
        slug: 'thriller',
        title: 'Thriller',
        artist: 'Michael Jackson',
        price: 29.99,
        image: '/img/thriller.jpg',
        year: 1982,
        genre: 'Pop',
        label: 'Epic Records',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Réédition 180g',
        description: "L'album le plus vendu de tous les temps. Thriller repousse les limites de la pop, du funk et du rock avec des productions signées Quincy Jones. De « Billie Jean » à « Beat It », chaque titre est devenu un classique intemporel.",
        tracklist: ['Wanna Be Startin\' Somethin\'', 'Baby Be Mine', 'The Girl Is Mine', 'Thriller', 'Beat It', 'Billie Jean', 'Human Nature', 'P.Y.T.', 'The Lady in My Life']
    },
    {
        id: 2,
        slug: 'happier-than-ever',
        title: 'Happier Than Ever',
        artist: 'Billie Eilish',
        price: 24.99,
        image: '/img/billie-eilish-happier-than-ever.webp',
        year: 2021,
        genre: 'Pop alternative',
        label: 'Darkroom / Interscope',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Deuxième album de Billie Eilish, explorant la célébrité et l'anxiété avec une maturité saisissante. La production minimaliste de Finneas met en valeur une voix plus assurée et des arrangements d'une élégance rare.",
        tracklist: ['Getting Older', 'I Didn\'t Change My Number', 'Billie Bossa Nova', 'my future', 'Oxytocin', 'GOLDWING', 'Lost Cause', 'Halley\'s Comet', 'Not My Responsibility', 'OverHeated', 'Everybody Dies', 'Your Power', 'NDA', 'Therefore I Am', 'Happier Than Ever', 'Male Fantasy']
    },
    {
        id: 3,
        slug: 'the-dark-side-of-the-moon',
        title: 'The Dark Side of the Moon',
        artist: 'Pink Floyd',
        price: 27.50,
        image: '/img/pink-floyd-the-dark-side-of-the-moon.webp',
        year: 1973,
        genre: 'Rock progressif',
        label: 'Harvest Records',
        format: 'LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Remaster 2016',
        description: "Chef-d'oeuvre du rock progressif explorant la folie, le temps et la mort. L'album est resté 937 semaines au Billboard 200. Sa pochette au prisme est un symbole de la culture rock.",
        tracklist: ['Speak to Me', 'Breathe', 'On the Run', 'Time', 'The Great Gig in the Sky', 'Money', 'Us and Them', 'Any Colour You Like', 'Brain Damage', 'Eclipse']
    },
    {
        id: 4,
        slug: 'discovery',
        title: 'Discovery',
        artist: 'Daft Punk',
        price: 26.00,
        image: '/img/daft-punk-discovery.webp',
        year: 2001,
        genre: 'Électronique',
        label: 'Virgin Records',
        format: 'Double LP',
        country: 'France',
        stock: 'in_stock',
        pressing: 'Réédition',
        description: "Discovery fusionne house, funk et pop dans un voyage sonore futuriste. L'album a inspiré le film Interstella 5555. « One More Time » et « Harder, Better, Faster, Stronger » restent des hymnes électroniques.",
        tracklist: ['One More Time', 'Aerodynamic', 'Digital Love', 'Harder, Better, Faster, Stronger', 'Crescendolls', 'Nightvision', 'Superheroes', 'High Life', 'Something About Us', 'Voyager', 'Veridis Quo', 'Short Circuit', 'Face to Face', 'Too Long']
    },
    {
        id: 5,
        slug: 'rumours',
        title: 'Rumours',
        artist: 'Fleetwood Mac',
        price: 22.90,
        image: '/img/fleetwood-mac-rumours.webp',
        year: 1977,
        genre: 'Rock',
        label: 'Warner Bros.',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Remaster 2004',
        description: "Enregistré en pleine tourmente sentimentale, Rumours transforme la douleur en or. « Dreams », « Go Your Own Way » et « The Chain » sont des standards absolus portés par des harmonies magistrales.",
        tracklist: ['Second Hand News', 'Dreams', 'Never Going Back Again', 'Don\'t Stop', 'Go Your Own Way', 'Songbird', 'The Chain', 'You Make Loving Fun', 'I Don\'t Want to Know', 'Oh Daddy', 'Gold Dust Woman']
    },
    {
        id: 6,
        slug: 'sauver-lamour',
        title: 'Sauver l\'amour',
        artist: 'Daniel Balavoine',
        price: 22.90,
        image: '/img/sauver-lamour.webp',
        year: 1985,
        genre: 'Variété française',
        label: 'Barclay',
        format: 'LP',
        country: 'France',
        stock: 'limited',
        pressing: 'Réédition',
        description: "Dernier album de Daniel Balavoine, testament musical d'une intensité rare. Le titre éponyme, avec ses synthétiseurs puissants et ses paroles engagées, reste un sommet de la chanson française des années 80.",
        tracklist: ['Sauver l\'amour', 'Tous les cris les S.O.S.', 'L\'Aziza', 'Aimer est plus fort que d\'être aimé', 'Partir avant les miens']
    },
    {
        id: 7,
        slug: 'elvis-30-hits',
        title: 'ELV1S 30 #1 Hits',
        artist: 'Elvis Presley',
        price: 21.90,
        image: '/img/elvis-presley-30-hits.webp',
        year: 2002,
        genre: 'Rock \'n\' Roll',
        label: 'RCA / Sony',
        format: 'Double LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Compilation définitive du King réunissant ses 30 numéros un. De « Heartbreak Hotel » à « Suspicious Minds », ce double vinyle retrace la carrière d'un artiste qui a inventé le rock'n'roll.",
        tracklist: ['Heartbreak Hotel', 'Don\'t Be Cruel', 'Hound Dog', 'Love Me Tender', 'Jailhouse Rock', 'All Shook Up', 'Suspicious Minds', 'Can\'t Help Falling in Love', 'Burning Love']
    },
    {
        id: 8,
        slug: 'dawn-fm',
        title: 'Dawn FM',
        artist: 'The Weeknd',
        price: 19.99,
        image: '/img/the-weeknd-dawn-fm.webp',
        year: 2022,
        genre: 'Synth-pop / R&B',
        label: 'XO / Republic',
        format: 'LP',
        country: 'Canada',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Voyage conceptuel à travers une station de radio fictive du purgatoire. Avec Max Martin et Jim Carrey, l'album mêle synth-pop 80s, new wave et R&B dans une esthétique rétro-futuriste.",
        tracklist: ['Dawn FM', 'Gasoline', 'How Do I Make You Love Me?', 'Take My Breath', 'Sacrifice', 'Out of Time', 'Here We Go... Again', 'Best Friends', 'Is There Someone Else?', 'Starry Eyes', 'Less Than Zero']
    },
    {
        id: 9,
        slug: 'adele-30',
        title: '30',
        artist: 'Adele',
        price: 21.90,
        image: '/img/adele-30.webp',
        year: 2021,
        genre: 'Pop / Soul',
        label: 'Columbia',
        format: 'LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Album du divorce et de la reconstruction, 30 est le disque le plus personnel d'Adele. « Easy On Me » a battu tous les records de streaming à sa sortie. Une voix plus puissante que jamais.",
        tracklist: ['Strangers by Nature', 'Easy On Me', 'My Little Love', 'Cry Your Heart Out', 'Oh My God', 'Can I Get It', 'I Drink Wine', 'All Night Parking', 'Woman Like Me', 'Hold On', 'To Be Loved', 'Love Is a Game']
    },
    {
        id: 10,
        slug: 'abbey-road',
        title: 'Abbey Road',
        artist: 'The Beatles',
        price: 28.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/4/42/Beatles_-_Abbey_Road.jpg',
        year: 1969,
        genre: 'Rock',
        label: 'Apple Records',
        format: 'LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Remaster 2019',
        description: "Dernier album enregistré par les Beatles. Le medley de la face B reste l'une des plus grandes réussites du rock. « Come Together » et « Here Comes the Sun » sont des classiques éternels.",
        tracklist: ['Come Together', 'Something', 'Maxwell\'s Silver Hammer', 'Oh! Darling', 'Octopus\'s Garden', 'I Want You', 'Here Comes the Sun', 'Because', 'You Never Give Me Your Money', 'Golden Slumbers', 'Carry That Weight', 'The End']
    },
    {
        id: 11,
        slug: 'back-to-black',
        title: 'Back to Black',
        artist: 'Amy Winehouse',
        price: 23.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/6/67/Amy_Winehouse_-_Back_to_Black_%28album%29.png',
        year: 2006,
        genre: 'Soul / Jazz',
        label: 'Island Records',
        format: 'LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Réédition 180g',
        description: "Soul brute et jazz fumé portés par la voix unique d'Amy Winehouse. Produit par Mark Ronson, il mêle sonorités Motown des années 60 à une écriture contemporaine déchirante.",
        tracklist: ['Rehab', 'You Know I\'m No Good', 'Me & Mr Jones', 'Just Friends', 'Back to Black', 'Love Is a Losing Game', 'Tears Dry on Their Own', 'Wake Up Alone', 'Some Unholy War', 'He Can Only Hold Her', 'Addicted']
    },
    {
        id: 12,
        slug: 'random-access-memories',
        title: 'Random Access Memories',
        artist: 'Daft Punk',
        price: 31.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/a/a7/Random_Access_Memories.jpg',
        year: 2013,
        genre: 'Électronique / Disco',
        label: 'Columbia',
        format: 'Double LP',
        country: 'France',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Lettre d'amour au disco, au funk et à la musique analogique. « Get Lucky » avec Pharrell et Nile Rodgers est devenu l'hymne de l'été 2013. Grammy de l'Album de l'année.",
        tracklist: ['Give Life Back to Music', 'The Game of Love', 'Giorgio by Moroder', 'Within', 'Instant Crush', 'Lose Yourself to Dance', 'Touch', 'Get Lucky', 'Beyond', 'Motherboard', 'Fragments of Time', 'Doin\' It Right', 'Contact']
    },
    {
        id: 13,
        slug: 'nevermind',
        title: 'Nevermind',
        artist: 'Nirvana',
        price: 25.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/b/b7/NirvanaNevermindalbumcover.jpg',
        year: 1991,
        genre: 'Grunge',
        label: 'DGC Records',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Remaster 2021',
        description: "Nevermind a propulsé le grunge dans le mainstream. « Smells Like Teen Spirit » est l'hymne d'une génération. L'énergie brute de Kurt Cobain et la production de Butch Vig en font un album fondateur.",
        tracklist: ['Smells Like Teen Spirit', 'In Bloom', 'Come as You Are', 'Breed', 'Lithium', 'Polly', 'Territorial Pissings', 'Drain You', 'Lounge Act', 'Stay Away', 'On a Plain', 'Something in the Way']
    },
    {
        id: 14,
        slug: 'kind-of-blue',
        title: 'Kind of Blue',
        artist: 'Miles Davis',
        price: 24.50,
        image: 'https://upload.wikimedia.org/wikipedia/en/9/9c/MilesDavisKindofBlue.jpg',
        year: 1959,
        genre: 'Jazz',
        label: 'Columbia',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Remaster 180g',
        description: "L'album de jazz le plus vendu de tous les temps. Kind of Blue a révolutionné le genre en introduisant le jazz modal. Avec John Coltrane et Bill Evans, une musique d'une beauté contemplative.",
        tracklist: ['So What', 'Freddie Freeloader', 'Blue in Green', 'All Blues', 'Flamenco Sketches']
    },
    {
        id: 15,
        slug: 'ok-computer',
        title: 'OK Computer',
        artist: 'Radiohead',
        price: 26.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Radioheadokcomputer.png',
        year: 1997,
        genre: 'Rock alternatif',
        label: 'Parlophone',
        format: 'Double LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Réédition',
        description: "Prophétie musicale sur l'aliénation technologique. Radiohead mêle rock, électronique et orchestrations dans un paysage sonore anxieux et magnifique. « Paranoid Android » et « Karma Police » sont des monuments.",
        tracklist: ['Airbag', 'Paranoid Android', 'Subterranean Homesick Alien', 'Exit Music (For a Film)', 'Let Down', 'Karma Police', 'Fitter Happier', 'Electioneering', 'Climbing Up the Walls', 'No Surprises', 'Lucky', 'The Tourist']
    },
    {
        id: 16,
        slug: 'melody-nelson',
        title: 'L\'Histoire de Melody Nelson',
        artist: 'Serge Gainsbourg',
        price: 27.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/b/b0/Melody_nelson.jpg',
        year: 1971,
        genre: 'Pop / Art rock',
        label: 'Philips',
        format: 'LP',
        country: 'France',
        stock: 'limited',
        pressing: 'Réédition 180g',
        description: "Album-concept racontant une histoire d'amour, considéré comme le chef-d'oeuvre de Gainsbourg. Les arrangements orchestraux de Jean-Claude Vannier en font un disque unique dans l'histoire de la musique française.",
        tracklist: ['Melody', 'Ballade de Melody Nelson', 'Valse de Melody', 'Ah ! Melody', 'L\'Hôtel particulier', 'En Melody', 'Cargo culte']
    },
    {
        id: 17,
        slug: 'ziggy-stardust',
        title: 'The Rise and Fall of Ziggy Stardust',
        artist: 'David Bowie',
        price: 26.50,
        image: 'https://upload.wikimedia.org/wikipedia/en/0/01/ZiggyStardust.jpg',
        year: 1972,
        genre: 'Glam rock',
        label: 'RCA Records',
        format: 'LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Remaster 2012',
        description: "Album-concept sur un rockeur extraterrestre, sommet du glam rock. Bowie y incarne un personnage androgyne qui a redéfini l'image du rock. « Starman » et « Suffragette City » sont légendaires.",
        tracklist: ['Five Years', 'Soul Love', 'Moonage Daydream', 'Starman', 'It Ain\'t Easy', 'Lady Stardust', 'Star', 'Hang On to Yourself', 'Ziggy Stardust', 'Suffragette City', 'Rock \'n\' Roll Suicide']
    },
    {
        id: 18,
        slug: 'homework',
        title: 'Homework',
        artist: 'Daft Punk',
        price: 24.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/9/9c/Daft_Punk_-_Homework.png',
        year: 1997,
        genre: 'Électronique / House',
        label: 'Virgin Records',
        format: 'Double LP',
        country: 'France',
        stock: 'in_stock',
        pressing: 'Réédition',
        description: "Premier album des Daft Punk, bombe de house music brute. « Around the World » et « Da Funk » ont défini le son de la French Touch et conquis les dancefloors du monde entier.",
        tracklist: ['Daftendirekt', 'WDPK 83.7 FM', 'Revolution 909', 'Da Funk', 'Phoenix', 'Fresh', 'Around the World', 'Rollin\' & Scratchin\'', 'Teachers', 'High Fidelity', 'Rock\'n Roll', 'Oh Yeah', 'Burnin\'', 'Indo Silver Club', 'Alive', 'Funk Ad']
    },
    {
        id: 19,
        slug: 'a-night-at-the-opera',
        title: 'A Night at the Opera',
        artist: 'Queen',
        price: 25.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/4/4d/Queen_A_Night_At_The_Opera.png',
        year: 1975,
        genre: 'Rock',
        label: 'EMI',
        format: 'LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Remaster 2011',
        description: "Contient « Bohemian Rhapsody », l'une des chansons les plus ambitieuses jamais enregistrées. Queen mêle rock, opéra et music-hall dans une production grandiose et une créativité sans limites.",
        tracklist: ['Death on Two Legs', 'Lazing on a Sunday Afternoon', 'I\'m in Love with My Car', 'You\'re My Best Friend', '\'39', 'Sweet Lady', 'Seaside Rendezvous', 'The Prophet\'s Song', 'Love of My Life', 'Good Company', 'Bohemian Rhapsody', 'God Save the Queen']
    },
    {
        id: 20,
        slug: 'purple-rain',
        title: 'Purple Rain',
        artist: 'Prince',
        price: 27.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/9/9c/Princepurplerain.jpg',
        year: 1984,
        genre: 'Pop / Funk / Rock',
        label: 'Warner Bros.',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Remaster 2017',
        description: "Chef-d'oeuvre de Prince fusionnant funk, rock, pop et new wave. « When Doves Cry », « Let's Go Crazy » et le titre éponyme sont des monuments de la musique populaire.",
        tracklist: ['Let\'s Go Crazy', 'Take Me with U', 'The Beautiful Ones', 'Computer Blue', 'Darling Nikki', 'When Doves Cry', 'I Would Die 4 U', 'Baby I\'m a Star', 'Purple Rain']
    },
    {
        id: 21,
        slug: 'whats-going-on',
        title: 'What\'s Going On',
        artist: 'Marvin Gaye',
        price: 24.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/8/84/MarvinGayeWhat%27sGoingOnalbumcover.jpg',
        year: 1971,
        genre: 'Soul / R&B',
        label: 'Tamla / Motown',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Réédition 180g',
        description: "Album engagé sur la guerre du Vietnam et les injustices sociales. Marvin Gaye abandonne les tubes Motown formatés pour une oeuvre personnelle, fluide et profondément humaine.",
        tracklist: ['What\'s Going On', 'What\'s Happening Brother', 'Flyin\' High', 'Save the Children', 'God Is Love', 'Mercy Mercy Me', 'Right On', 'Wholy Holy', 'Inner City Blues']
    },
    {
        id: 22,
        slug: 'led-zeppelin-iv',
        title: 'Led Zeppelin IV',
        artist: 'Led Zeppelin',
        price: 26.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/2/26/Led_Zeppelin_-_Led_Zeppelin_IV.jpg',
        year: 1971,
        genre: 'Hard rock',
        label: 'Atlantic Records',
        format: 'LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Remaster 2014',
        description: "Contient « Stairway to Heaven », le morceau de rock le plus diffusé de l'histoire. L'album alterne entre folk acoustique et hard rock dévastateur avec une maîtrise absolue.",
        tracklist: ['Black Dog', 'Rock and Roll', 'The Battle of Evermore', 'Stairway to Heaven', 'Misty Mountain Hop', 'Four Sticks', 'Going to California', 'When the Levee Breaks']
    },
    {
        id: 23,
        slug: 'igor',
        title: 'IGOR',
        artist: 'Tyler, The Creator',
        price: 23.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/8/8b/Igor_-_Tyler%2C_the_Creator.jpg',
        year: 2019,
        genre: 'Neo-soul / Hip-hop',
        label: 'Columbia',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Album-concept sur un triangle amoureux, porté par des productions soul, funk et synthpop audacieuses. Tyler abandonne le rap pur pour un univers musical riche et expérimental. N°1 au Billboard.",
        tracklist: ['IGOR\'S THEME', 'EARFQUAKE', 'I THINK', 'RUNNING OUT OF TIME', 'NEW MAGIC WAND', 'A BOY IS A GUN*', 'PUPPET', 'WHAT\'S GOOD', 'GONE, GONE / THANK YOU', 'I DON\'T LOVE YOU ANYMORE', 'ARE WE STILL FRIENDS?']
    },
    {
        id: 24,
        slug: 'blonde',
        title: 'Blonde',
        artist: 'Frank Ocean',
        price: 34.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg',
        year: 2016,
        genre: 'R&B alternatif',
        label: 'Boys Don\'t Cry',
        format: 'Double LP',
        country: 'États-Unis',
        stock: 'limited',
        pressing: 'Standard',
        description: "Chef-d'oeuvre de R&B minimaliste et introspectif. Frank Ocean déconstruit les structures traditionnelles pour un paysage sonore onirique. « Nights » et « White Ferrari » sont des sommets d'émotion.",
        tracklist: ['Nikes', 'Ivy', 'Pink + White', 'Be Yourself', 'Solo', 'Skyline To', 'Self Control', 'Good Guy', 'Nights', 'Solo (Reprise)', 'Pretty Sweet', 'Close to You', 'White Ferrari', 'Seigfried', 'Godspeed', 'Futura Free']
    },
    {
        id: 25,
        slug: 'lemonade',
        title: 'Lemonade',
        artist: 'Beyoncé',
        price: 32.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/5/53/Beyonce_-_Lemonade_%28Official_Album_Cover%29.png',
        year: 2016,
        genre: 'R&B / Pop',
        label: 'Parkwood / Columbia',
        format: 'Double LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Album visuel explorant l'infidélité, la résilience et l'identité noire américaine. Beyoncé mêle R&B, rock, country et spoken word. « Formation » est devenu un hymne culturel.",
        tracklist: ['Pray You Catch Me', 'Hold Up', 'Don\'t Hurt Yourself', 'Sorry', '6 Inch', 'Daddy Lessons', 'Love Drought', 'Sandcastles', 'Forward', 'Freedom', 'All Night', 'Formation']
    },
    {
        id: 26,
        slug: 'wish-you-were-here',
        title: 'Wish You Were Here',
        artist: 'Pink Floyd',
        price: 26.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Pink_Floyd%2C_Wish_You_Were_Here_%281975%29.png',
        year: 1975,
        genre: 'Rock progressif',
        label: 'Harvest Records',
        format: 'LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Remaster 2016',
        description: "Hommage à Syd Barrett, fondateur du groupe sombré dans la folie. « Shine On You Crazy Diamond » et le titre éponyme sont des morceaux d'une beauté mélancolique absolue.",
        tracklist: ['Shine On You Crazy Diamond (Parts I-V)', 'Welcome to the Machine', 'Have a Cigar', 'Wish You Were Here', 'Shine On You Crazy Diamond (Parts VI-IX)']
    },
    {
        id: 27,
        slug: 'to-pimp-a-butterfly',
        title: 'To Pimp a Butterfly',
        artist: 'Kendrick Lamar',
        price: 28.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/f/f6/Kendrick_Lamar_-_To_Pimp_a_Butterfly.png',
        year: 2015,
        genre: 'Hip-hop',
        label: 'Top Dawg / Interscope',
        format: 'Double LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Oeuvre monumentale mêlant hip-hop, jazz, funk et spoken word. Kendrick Lamar explore l'identité noire et la culpabilité du survivant. « Alright » est devenu l'hymne du mouvement Black Lives Matter.",
        tracklist: ['Wesley\'s Theory', 'For Free?', 'King Kunta', 'Institutionalized', 'These Walls', 'u', 'Alright', 'For Sale?', 'Momma', 'Hood Politics', 'How Much a Dollar Cost', 'Complexion', 'The Blacker the Berry', 'You Ain\'t Gotta Lie', 'i', 'Mortal Man']
    },
    {
        id: 28,
        slug: 'the-wall',
        title: 'The Wall',
        artist: 'Pink Floyd',
        price: 34.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/1/13/PinkFloydWallCoverOriginalNoText.jpg',
        year: 1979,
        genre: 'Rock progressif',
        label: 'Harvest Records',
        format: 'Double LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Remaster 2016',
        description: "Opéra-rock sur l'isolement et la folie. Roger Waters raconte l'histoire de Pink, rockstar qui se coupe du monde. « Another Brick in the Wall » et « Comfortably Numb » sont des classiques universels.",
        tracklist: ['In the Flesh?', 'The Thin Ice', 'Another Brick in the Wall Pt. 2', 'Mother', 'Goodbye Blue Sky', 'Young Lust', 'Comfortably Numb', 'The Show Must Go On', 'Run Like Hell', 'The Trial', 'Outside the Wall']
    },
    {
        id: 29,
        slug: 'appetite-for-destruction',
        title: 'Appetite for Destruction',
        artist: 'Guns N\' Roses',
        price: 25.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/6/60/GnsR--AppetiteForDestworktion.jpg',
        year: 1987,
        genre: 'Hard rock',
        label: 'Geffen Records',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Remaster 2018',
        description: "L'un des débuts les plus explosifs du rock. « Welcome to the Jungle », « Sweet Child O' Mine » et « Paradise City » sont des hymnes de stade. L'énergie brute de cet album reste inégalée.",
        tracklist: ['Welcome to the Jungle', 'It\'s So Easy', 'Nightrain', 'Out ta Get Me', 'Mr. Brownstone', 'Paradise City', 'My Michelle', 'Think About You', 'Sweet Child O\' Mine', 'You\'re Crazy', 'Anything Goes', 'Rocket Queen']
    },
    {
        id: 30,
        slug: 'hotel-california',
        title: 'Hotel California',
        artist: 'Eagles',
        price: 24.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/4/49/Eagles_-_Hotel_California.jpg',
        year: 1976,
        genre: 'Rock',
        label: 'Asylum Records',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Réédition 180g',
        description: "Méditation sur l'excès et le rêve américain. Le titre éponyme, avec son solo de guitare légendaire, est l'un des morceaux les plus reconnaissables du rock. Certifié 26 fois platine.",
        tracklist: ['Hotel California', 'New Kid in Town', 'Life in the Fast Lane', 'Wasted Time', 'Victim of Love', 'Pretty Maids All in a Row', 'Try and Love Again', 'The Last Resort']
    },
    {
        id: 31,
        slug: 'future-nostalgia',
        title: 'Future Nostalgia',
        artist: 'Dua Lipa',
        price: 22.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/f/f5/Dua_Lipa_-_Future_Nostalgia_%28Official_Album_Cover%29.png',
        year: 2020,
        genre: 'Disco-pop',
        label: 'Warner Records',
        format: 'LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Explosion de disco-pop moderne qui a dominé les charts. Dua Lipa canalise les sonorités des années 80 avec une production impeccable. « Don't Start Now » et « Levitating » sont des tubes imparables.",
        tracklist: ['Future Nostalgia', 'Don\'t Start Now', 'Cool', 'Physical', 'Levitating', 'Pretty Please', 'Hallucinate', 'Love Again', 'Break My Heart', 'Good in Bed', 'Boys Will Be Boys']
    },
    {
        id: 32,
        slug: 'born-to-run',
        title: 'Born to Run',
        artist: 'Bruce Springsteen',
        price: 23.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/8/85/Born_to_Run_%28Front_Cover%29.jpg',
        year: 1975,
        genre: 'Rock',
        label: 'Columbia',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Remaster 2015',
        description: "L'album qui a fait de Springsteen « le futur du rock'n'roll ». Arrangements épiques, textes cinématographiques et énergie désespérée capturant le rêve américain de la classe ouvrière.",
        tracklist: ['Thunder Road', 'Tenth Avenue Freeze-Out', 'Night', 'Backstreets', 'Born to Run', 'She\'s the One', 'Meeting Across the River', 'Jungleland']
    },
    {
        id: 33,
        slug: 'good-kid-maad-city',
        title: 'good kid, m.A.A.d city',
        artist: 'Kendrick Lamar',
        price: 25.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/9/93/Kendrick_Lamar_-_Good_Kid_Maad_City.jpg',
        year: 2012,
        genre: 'Hip-hop',
        label: 'Top Dawg / Interscope',
        format: 'Double LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Autobiographie musicale de Kendrick Lamar grandissant à Compton. L'album alterne entre récits de rue, introspection et beats innovants. « Swimming Pools » et « Bitch, Don't Kill My Vibe » ont marqué le hip-hop.",
        tracklist: ['Sherane', 'Bitch, Don\'t Kill My Vibe', 'Backseat Freestyle', 'The Art of Peer Pressure', 'Money Trees', 'Poetic Justice', 'good kid', 'm.A.A.d city', 'Swimming Pools (Drank)', 'Sing About Me, I\'m Dying of Thirst', 'Real', 'Compton']
    },
    {
        id: 34,
        slug: 'legend',
        title: 'Legend',
        artist: 'Bob Marley & The Wailers',
        price: 22.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/e/e1/BobMarley-Legend.jpg',
        year: 1984,
        genre: 'Reggae',
        label: 'Island Records',
        format: 'LP',
        country: 'Jamaïque',
        stock: 'in_stock',
        pressing: 'Réédition 180g',
        description: "Compilation posthume la plus vendue de l'histoire. De « No Woman, No Cry » à « Redemption Song », chaque morceau porte un message d'amour et de résistance qui transcende les frontières.",
        tracklist: ['Is This Love', 'No Woman, No Cry', 'Could You Be Loved', 'Three Little Birds', 'Buffalo Soldier', 'Get Up, Stand Up', 'Stir It Up', 'One Love', 'I Shot the Sheriff', 'Waiting in Vain', 'Redemption Song', 'Jamming']
    },
    {
        id: 35,
        slug: 'after-hours',
        title: 'After Hours',
        artist: 'The Weeknd',
        price: 23.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/c/c1/The_Weeknd_-_After_Hours.png',
        year: 2020,
        genre: 'Synth-pop / R&B',
        label: 'XO / Republic',
        format: 'LP',
        country: 'Canada',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Plongée dans les ténèbres de Las Vegas avec une esthétique 80s sombre. « Blinding Lights » est devenu le single le plus streamé de l'histoire de Spotify. Consécration mondiale de The Weeknd.",
        tracklist: ['Alone Again', 'Too Late', 'Hardest to Love', 'Scared to Live', 'Snowchild', 'Escape from LA', 'Heartless', 'Faith', 'Blinding Lights', 'In Your Eyes', 'Save Your Tears', 'After Hours', 'Until I Bleed Out']
    },
    {
        id: 36,
        slug: 'miseducation-lauryn-hill',
        title: 'The Miseducation of Lauryn Hill',
        artist: 'Lauryn Hill',
        price: 26.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/9/9c/LaurynHillTheMiseducationofLaurynHillalbumcover.jpg',
        year: 1998,
        genre: 'Neo-soul / Hip-hop',
        label: 'Ruffhouse / Columbia',
        format: 'Double LP',
        country: 'États-Unis',
        stock: 'limited',
        pressing: 'Réédition',
        description: "Premier et unique album solo de Lauryn Hill, chef-d'oeuvre de neo-soul mêlant hip-hop, R&B et reggae. « Doo Wop (That Thing) » et « Everything Is Everything » sont des classiques. 5 Grammy Awards.",
        tracklist: ['Intro', 'Lost Ones', 'Ex-Factor', 'To Zion', 'Doo Wop (That Thing)', 'Superstar', 'Final Hour', 'When It Hurts So Bad', 'I Used to Love Him', 'Forgive Them Father', 'Every Ghetto, Every City', 'Nothing Even Matters', 'Everything Is Everything']
    },
    {
        id: 37,
        slug: 'channel-orange',
        title: 'Channel Orange',
        artist: 'Frank Ocean',
        price: 29.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg',
        year: 2012,
        genre: 'R&B alternatif',
        label: 'Def Jam',
        format: 'Double LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Premier album officiel de Frank Ocean, mosaïque de R&B progressif et de pop expérimentale. « Thinkin Bout You » et « Pyramids » ont redéfini les possibilités du genre.",
        tracklist: ['Start', 'Thinkin Bout You', 'Fertilizer', 'Sierra Leone', 'Sweet Life', 'Super Rich Kids', 'Pilot Jones', 'Crack Rock', 'Pyramids', 'Lost', 'White', 'Monks', 'Bad Religion', 'Pink Matter', 'Forrest Gump', 'End']
    },
    {
        id: 38,
        slug: 'is-this-it',
        title: 'Is This It',
        artist: 'The Strokes',
        price: 22.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/5/57/The_Strokes_-_Is_This_It_cover.png',
        year: 2001,
        genre: 'Rock alternatif',
        label: 'RCA Records',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Réédition',
        description: "Is This It a relancé le rock indé au début des années 2000. Garage rock new-yorkais nonchalant et irrésistible. « Last Nite » et « Someday » sont les hymnes d'une nouvelle génération.",
        tracklist: ['Is This It', 'The Modern Age', 'Soma', 'Barely Legal', 'Someday', 'Alone, Together', 'Last Nite', 'Hard to Explain', 'New York City Cops', 'Trying Your Luck', 'Take It or Leave It']
    },
    {
        id: 39,
        slug: 'ces-gens-la',
        title: 'Ces gens-là',
        artist: 'Jacques Brel',
        price: 24.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/3/3f/Jacques_Brel_-_Ces_gens-l%C3%A0.jpg',
        year: 1966,
        genre: 'Chanson française',
        label: 'Barclay',
        format: 'LP',
        country: 'Belgique',
        stock: 'limited',
        pressing: 'Réédition 180g',
        description: "Contenant certaines des plus grandes chansons de Jacques Brel, dont le portrait acide « Ces gens-là ». La puissance vocale et théâtrale de Brel, combinée à des orchestrations somptueuses, en fait un monument.",
        tracklist: ['Ces gens-là', 'Jef', 'La Fanette', 'Grand-mère', 'Les Bergers', 'Le Tango funèbre', 'Fernand', 'Les Désespérés', 'L\'Âge idiot', 'La Chanson de Jacky']
    },
    {
        id: 40,
        slug: 'currents',
        title: 'Currents',
        artist: 'Tame Impala',
        price: 27.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/9/9b/Tame_Impala_-_Currents.png',
        year: 2015,
        genre: 'Psychédélique / Synth-pop',
        label: 'Modular / Interscope',
        format: 'Double LP',
        country: 'Australie',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Métamorphose de Tame Impala, du rock psychédélique à la synth-pop luxuriante. Kevin Parker explore la rupture avec des productions hypnotiques. « Let It Happen » et « The Less I Know the Better » sont cultes.",
        tracklist: ['Let It Happen', 'Nangs', 'The Moment', 'Yes I\'m Changing', 'Eventually', 'Gossip', 'Past Life', 'Disciples', 'Cause I\'m a Man', 'Reality in Motion', 'Love/Paranoia', 'New Person, Same Old Mistakes']
    },
    {
        id: 41,
        slug: 'am',
        title: 'AM',
        artist: 'Arctic Monkeys',
        price: 23.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/0/04/Arctic_Monkeys_-_AM.png',
        year: 2013,
        genre: 'Rock alternatif',
        label: 'Domino',
        format: 'LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Album de la consécration mondiale des Arctic Monkeys. Alex Turner mêle riffs lourds, influences hip-hop et crooning séducteur. « Do I Wanna Know? » et « R U Mine? » sont des tubes planétaires.",
        tracklist: ['Do I Wanna Know?', 'R U Mine?', 'One for the Road', 'Arabella', 'I Wanna Be Yours', 'No. 1 Party Anthem', 'Mad Sounds', 'Fireside', 'Why\'d You Only Call Me When You\'re High?', 'Snap Out of It', 'Knee Socks', 'I Wanna Be Yours']
    },
    {
        id: 42,
        slug: 'the-suburbs',
        title: 'The Suburbs',
        artist: 'Arcade Fire',
        price: 26.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/a/a1/Arcade_Fire_-_The_Suburbs.jpg',
        year: 2010,
        genre: 'Indie rock',
        label: 'Merge Records',
        format: 'Double LP',
        country: 'Canada',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Album-concept sur la banlieue et la nostalgie de l'enfance. The Suburbs a remporté le Grammy de l'Album de l'année, consacrant Arcade Fire comme l'un des groupes les plus importants de sa génération.",
        tracklist: ['The Suburbs', 'Ready to Start', 'Modern Man', 'Rococo', 'Empty Room', 'City with No Children', 'Half Light I', 'Half Light II', 'Suburban War', 'Month of May', 'Wasted Hours', 'Deep Blue', 'We Used to Wait', 'Sprawl I', 'Sprawl II', 'The Suburbs (Continued)']
    },
    {
        id: 43,
        slug: 'in-rainbows',
        title: 'In Rainbows',
        artist: 'Radiohead',
        price: 25.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/2/2e/In_Rainbows_Official_Cover.jpg',
        year: 2007,
        genre: 'Rock alternatif',
        label: 'XL Recordings',
        format: 'LP',
        country: 'Royaume-Uni',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Sorti en « pay what you want », In Rainbows est l'album le plus chaleureux de Radiohead. « Reckoner », « Nude » et « Weird Fishes » offrent une beauté sonore enveloppante et émotionnelle.",
        tracklist: ['15 Step', 'Bodysnatchers', 'Nude', 'Weird Fishes/Arpeggi', 'All I Need', 'Faust Arp', 'Reckoner', 'House of Cards', 'Jigsaw Falling into Place', 'Videotape']
    },
    {
        id: 44,
        slug: 'the-velvet-underground-and-nico',
        title: 'The Velvet Underground & Nico',
        artist: 'The Velvet Underground',
        price: 27.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Velvet_Underground_and_Nico.jpg',
        year: 1967,
        genre: 'Art rock',
        label: 'Verve Records',
        format: 'LP',
        country: 'États-Unis',
        stock: 'limited',
        pressing: 'Réédition 180g',
        description: "Produit par Andy Warhol, cet album a influencé le punk, le new wave et le rock indépendant. La pochette à la banane est iconique. « Sunday Morning » et « Heroin » sont des pierres angulaires du rock.",
        tracklist: ['Sunday Morning', 'I\'m Waiting for the Man', 'Femme Fatale', 'Venus in Furs', 'Run Run Run', 'All Tomorrow\'s Parties', 'Heroin', 'There She Goes Again', 'I\'ll Be Your Mirror', 'The Black Angel\'s Death Song', 'European Son']
    },
    {
        id: 45,
        slug: 'remain-in-light',
        title: 'Remain in Light',
        artist: 'Talking Heads',
        price: 24.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/4/43/Talking_Heads_-_Remain_in_Light.png',
        year: 1980,
        genre: 'New wave / Art rock',
        label: 'Sire Records',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Réédition',
        description: "Fusion révolutionnaire de new wave, funk africain et électronique. Produit avec Brian Eno, Remain in Light est un album visionnaire. « Once in a Lifetime » est devenu un classique absolu.",
        tracklist: ['Born Under Punches', 'Crosseyed and Painless', 'The Great Curve', 'Once in a Lifetime', 'Houses in Motion', 'Seen and Not Seen', 'Listening Wind', 'The Overload']
    },
    {
        id: 46,
        slug: 'noir-desir-des-visages-des-figures',
        title: 'Des visages des figures',
        artist: 'Noir Désir',
        price: 23.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Des_visages_des_figures.jpg',
        year: 2001,
        genre: 'Rock alternatif',
        label: 'Barclay',
        format: 'LP',
        country: 'France',
        stock: 'limited',
        pressing: 'Réédition',
        description: "Dernier album studio de Noir Désir, mêlant rock, électronique et poésie engagée. « Le vent nous portera » est devenu un hymne générationnel. L'album le plus abouti du groupe bordelais.",
        tracklist: ['Le vent nous portera', 'L\'Homme pressé', 'Des armes', 'Les Persiennes', 'Le Grand incendie', 'À ton étoile', 'Bouquet de nerfs', 'Des visages des figures']
    },
    {
        id: 47,
        slug: 'loveless',
        title: 'Loveless',
        artist: 'My Bloody Valentine',
        price: 29.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/4/4a/MyBloodyValentineLoveless.jpg',
        year: 1991,
        genre: 'Shoegaze',
        label: 'Creation Records',
        format: 'LP',
        country: 'Irlande',
        stock: 'limited',
        pressing: 'Remaster 2021',
        description: "Album fondateur du shoegaze, Loveless a redéfini ce que la guitare pouvait faire. Kevin Shields crée un mur de son hypnotique et enveloppant. « Only Shallow » et « When You Sleep » sont des expériences sonores uniques.",
        tracklist: ['Only Shallow', 'Loomer', 'Touched', 'To Here Knows When', 'When You Sleep', 'I Only Said', 'Come in Alone', 'Sometimes', 'Blown a Wish', 'What You Want', 'Soon']
    },
    {
        id: 48,
        slug: 'man-on-the-moon',
        title: 'Man on the Moon II',
        artist: 'Kid Cudi',
        price: 24.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Kid_Cudi_-_Man_on_the_Moon_II_-_The_Legend_of_Mr._Rager.jpg',
        year: 2010,
        genre: 'Hip-hop',
        label: 'G.O.O.D. Music / Universal',
        format: 'Double LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Suite du voyage introspectif de Kid Cudi, Man on the Moon II explore la dépression et la solitude avec une honnêteté brute. « Mr. Rager » et « Erase Me » sont des morceaux emblématiques du hip-hop émotionnel.",
        tracklist: ['Scott Mescudi vs. the World', 'Revofev', 'Don\'t Play This Song', 'We Aite', 'Marijuana', 'Mojo So Dope', 'Ashin\' Kusher', 'Erase Me', 'Mr. Rager', 'These Worries', 'The End', 'All Along', 'Ghost!', 'Maniac', 'Trapped in My Mind', 'DONT PLAY THIS SONG']
    },
    {
        id: 49,
        slug: 'ctrl',
        title: 'Ctrl',
        artist: 'SZA',
        price: 23.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/a/a0/SZA_-_Ctrl.png',
        year: 2017,
        genre: 'R&B alternatif',
        label: 'Top Dawg / RCA',
        format: 'LP',
        country: 'États-Unis',
        stock: 'in_stock',
        pressing: 'Standard',
        description: "Premier album de SZA, Ctrl est un journal intime musical explorant l'amour, l'insécurité et l'indépendance. « Love Galore » et « The Weekend » ont fait de SZA une voix incontournable du R&B moderne.",
        tracklist: ['Supermodel', 'Love Galore', 'Doves in the Wind', 'Drew Barrymore', 'Prom', 'The Weekend', 'Go Gina', 'Garden (Say It Like Dat)', 'Broken Clocks', 'Anything', 'Wavy', 'Normal Girl', 'Pretty Little Birds', '20 Something']
    },
    {
        id: 50,
        slug: 'un-jour-en-france',
        title: 'L\'Homme qui marche',
        artist: 'Noir Désir',
        price: 22.90,
        image: 'https://upload.wikimedia.org/wikipedia/en/7/7e/666.667_Club.jpg',
        year: 1999,
        genre: 'Rock alternatif',
        label: 'Barclay',
        format: 'LP',
        country: 'France',
        stock: 'in_stock',
        pressing: 'Réédition',
        description: "Album brut et engagé de Noir Désir, porté par l'énergie de Bertrand Cantat. « Un jour en France » est un classique du rock français. L'album capture la rage et la poésie du groupe à son apogée scénique.",
        tracklist: ['Un jour en France', 'L\'Homme pressé', 'Comme elle vient', 'À la longue', 'Prayer for a Wanker', 'Fin de siècle', 'Septembre, en attendant', 'Ernestine']
    },
]

// ---------------------------------------------------------------------------
// Fonctions utilitaires
// ---------------------------------------------------------------------------

// Tous les produits (alias pour compatibilité)
export const featuredProducts = products.slice(0, 9)

// Trouver un produit par son slug (utilisé par la page /produit/[slug])
export function getProductBySlug(slug) {
    return products.find(p => p.slug === slug) || null
}

// Trouver des produits similaires (même genre ou même artiste, max 4)
export function getRelatedProducts(product, max = 4) {
    if (!product) return []
    return products
        .filter(p => p.id !== product.id && (p.genre === product.genre || p.artist === product.artist))
        .slice(0, max)
}

// Texte lisible pour le stock
export function getStockLabel(stock) {
    const labels = {
        in_stock: 'En stock',
        limited: 'Stock limité',
        out_of_stock: 'Rupture de stock'
    }
    return labels[stock] || 'Indisponible'
}
